name: CI Checks

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: ğŸ§ª Testing (Unit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare-project/

      - name: Testing
        run: ./.github/actions/unit-tests/

  checks:
    name: ğŸ” Static Analysis & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare-project/

      - name: Checks
        uses: ./.github/actions/checks/

  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare
        uses: ./.github/actions/prepare-project/

      - name: Check packages build
        run: pnpm build
